### ISSUE TITLE
office365ConnectorSend stopped working with Jenkins 2.387.1

### ISSUE THREAD

**Issue by d066471** [jenkinsci/office-365-connector-plugin#306]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
Jenkins: 2.387.1
OS: Linux - 5.10.162+
Java: 11.0.18 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Office-365-Connector:4.14.0
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux Ubuntu

### Reproduction steps

1. Create a webhook URL for a teams channel.
2. Provide this URL as a property to office365ConnectorSend
3. Run the pipeline and it fails with following error:

07:24:20  Masking supported pattern matches of $WEBHOOK_URL
07:24:20  [Pipeline] {
07:24:20  [Pipeline] office365ConnectorSend
07:24:20  [Pipeline] }
07:24:20  [Pipeline] // withCredentials
07:24:20  [Pipeline] }
07:24:20  [Pipeline] // stage
07:24:20  [Pipeline] }
07:24:20  [Pipeline] // node
07:24:20  [Pipeline] End of Pipeline
07:24:20  java.lang.ClassNotFoundException: org.apache.commons.httpclient.Credentials
07:24:20  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
07:24:20  	at jenkins.util.URLClassLoader2.findClass(URLClassLoader2.java:35)
07:24:20  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
07:24:20  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
07:24:20  Caused: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/Credentials
07:24:20  	at jenkins.plugins.office365connector.Office365ConnectorWebhookNotifier.executeWorker(Office365ConnectorWebhookNotifier.java:115)
07:24:20  	at jenkins.plugins.office365connector.Office365ConnectorWebhookNotifier.sendBuildStepNotification(Office365ConnectorWebhookNotifier.java:108)
07:24:20  	at jenkins.plugins.office365connector.workflow.Execution.run(Execution.java:33)
07:24:20  	at jenkins.plugins.office365connector.workflow.Execution.run(Execution.java:15)
07:24:20  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
07:24:20  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
07:24:20  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
07:24:20  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
07:24:20  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
07:24:20  	at java.base/java.lang.Thread.run(Thread.java:829)
07:24:20  
07:24:20  GitHub has been notified of this commit’s build result

### Expected Results

Pipeline should run green. 

### Actual Results

Pipeline failed while communicating with office365ConnectorSend API

### Anything else?

New webhook URL was created but it still does not work.

**Comment by AxxlFoley** [comment]
@d066471  Upgrade to the latest version of the plugin (v 4.18.0) fixed our issue.

**Comment by d066471** [comment]
Updating to Office 365 Connector v4.18.0 should resolve the issue.
